#Student Performance Analytics
###Week 2-3 examination


####Dataset :

In [ ]:
import pandas as pd

data = {
    "student_id": ["2026CS001","2026CS002","2026IT001","2026IT002","2026CE001","2026CE002","2026CS003","2026IT003"],
    "name": ["Aditi","Bhavana","Chaitra","Divya","Esha","Fatima","Gauri","Harshada"],
    "department": ["Computer Engineering","Computer Engineering","Information Technology","Information Technology","Civil Engineering","Civil Engineering","Computer Engineering","Information Technology"],
    "attendance_pct": [92,64,78,55,88,71,96,43],
    "diary_entries": [12,6,9,4,10,8,14,2],
    "tasks_completed": [8,5,7,3,8,6,9,2],
    "assignment_score": [84,58,72,46,79,66,91,35],
    "lab_score": [88,61,76,52,82,69,94,41]
}

df = pd.DataFrame(data)

df.to_csv("week_2_3_exam_student_signals.csv", index=False)
from google.colab import files

files.download("week_2_3_exam_student_signals.csv")

print("CSV file created successfully!")
df.head()

CSV file created successfully!

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76
3,2026IT002,Divya,Information Technology,55,4,3,46,52
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82

**Load Dataset :**

In [ ]:
import pandas as pd

df = pd.read_csv("week_2_3_exam_student_signals.csv")

df.head()

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76
3,2026IT002,Divya,Information Technology,55,4,3,46,52
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82

###Markdown Cell

The dataset is loaded from the csv file and the 5 rows are displayed.

**Check Data :**

In [ ]:
print("Data Types")
print(df.dtypes)

print("\nMissing Values")
print(df.isnull().sum())

print("\nShape")
print(df.shape)

Data Types
student_id          object
name                object
department          object
attendance_pct       int64
diary_entries        int64
tasks_completed      int64
assignment_score     int64
lab_score            int64
dtype: object

Missing Values
student_id          0
name                0
department          0
attendance_pct      0
diary_entries       0
tasks_completed     0
assignment_score    0
lab_score           0
dtype: int64

Shape
(8, 8)

###Markdown Cell

This section checks the data types, missing values, and the shape of the dataset.

**Readiness Score Function :**

In [ ]:
def readiness_score(attendance, diary, tasks, assignment, lab):
    score = (attendance*0.3) + (diary*2) + (tasks*3) + (assignment*0.2) + (lab*0.2)
    return round(score,2)

df["Readiness Score"] = df.apply(
    lambda x: readiness_score(
        x["attendance_pct"],
        x["diary_entries"],
        x["tasks_completed"],
        x["assignment_score"],
        x["lab_score"]
    ),
    axis=1
)

df.head()

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score,Readiness Score
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88,110.0
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61,70.0
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76,92.0
3,2026IT002,Divya,Information Technology,55,4,3,46,52,53.1
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82,102.6

###Markdown Cell

This function is used to calculate the readiness score for each student.

**Classification :**

In [ ]:
bands=[]

for score in df["Readiness Score"]:
    if score>=90:
        bands.append("Excellent")
    elif score>=70:
        bands.append("Strong")
    elif score>=50:
        bands.append("Developing")
    else:
        bands.append("Support")

df["Performance Band"]=bands

df

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score,Readiness Score,Performance Band
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88,110.0,Excellent
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61,70.0,Strong
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76,92.0,Excellent
3,2026IT002,Divya,Information Technology,55,4,3,46,52,53.1,Developing
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82,102.6,Excellent
5,2026CE002,Fatima,Civil Engineering,71,8,6,66,69,82.3,Strong
6,2026CS003,Gauri,Computer Engineering,96,14,9,91,94,120.8,Excellent
7,2026IT003,Harshada,Information Technology,43,2,2,35,41,38.1,Support

###Markdown Cell

Students are classified as Support, Developing, Strong, or Excellent based on their readiness score.

**Analytics :**

Department Average :

In [ ]:
print("Department Average")
print(df.groupby("department")["Readiness Score"].mean())

Department Average
department
Civil Engineering          92.450000
Computer Engineering      100.266667
Information Technology     61.066667
Name: Readiness Score, dtype: float64

Top Performer :

In [ ]:
print("\nTop Performer")
print(df.loc[df["Readiness Score"].idxmax()])

Top Performer
student_id                     2026CS003
name                               Gauri
department          Computer Engineering
attendance_pct                        96
diary_entries                         14
tasks_completed                        9
assignment_score                      91
lab_score                             94
Readiness Score                    120.8
Performance Band               Excellent
Name: 6, dtype: object

Students Needing Support :

In [ ]:
print("\nStudents Needing Support")
print(df[df["Performance Band"]=="Support"])

Students Needing Support
  student_id      name              department  attendance_pct  diary_entries  \
7  2026IT003  Harshada  Information Technology              43              2

   tasks_completed  assignment_score  lab_score  Readiness Score  \
7                2                35         41             38.1

  Performance Band
7          Support

###Markdown Cell

This section shows:
- Department average readiness score
- Top-performing student
- Students who need support

**Expected Output :**

####Department Average:

Civil Engineering          61.90

Computer Engineering       72.53

 Information Technology     53.37

####Top Performer

 Name : Gauri

Performance Band : Strong

####Students Needing Support

Harshada

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

###Inetrpretation section :

*Which department appears strongest in the dataset and why?*

Answer->

The **Computer Engineering** department appears to be the strongest because it has the highest average readiness score. Students in this department have better attendance, complete more tasks, and achieve higher assignment and lab scores.

-------------------------------------------------------------------------------

*Which students need immediate academic support and what signals show that?*

Answer->

**Harshada** needs immediate academic support because of low attendance, fewer diary entries, fewer completed tasks, and low assignment and lab scores. These signals indicate that the student is struggling and requires additional guidance.

-------------------------------------------------------------------------------
*3. What is one limitation of this small dataset?*

Answer->

The dataset contains only **8 students**, so it is too small to represent the performance of all students accurately.

-------------------------------------------------------------------------------

*What extra columns would make the analysis more useful for the internship team?*

Answer->

The analysis would be more useful if the dataset included:
- Quiz scores
- Mid-semester exam marks
- Project performance
- Class participation or attendance by week